CREATE TABLE STOCKGROUP(
	Id CHAR(36) PRIMARY KEY,
	Code NVARCHAR(20) NOT NULL,
	Description NVARCHAR(255),
	Remarks NVARCHAR(255),
	CreatedAt DATETIME NOT NULL,
	CreatedBy CHAR(36) NOT NULL,
	UpdatedAt DATETIME,
	UpdatedBy CHAR(36),
	Ip NVARCHAR(MAX) NOT NULL,
	IsActive BIT NOT NULL
);