CREATE TABLE SUPPLIER(
	ID CHAR(36) PRIMARY KEY,
	NAME NVARCHAR(255) NOT NULL,
	EMAIL NVARCHAR(255) NULL,
	PHONE NVARCHAR(255) NULL,
	ADDRESS NVARCHAR(255) NULL,
	REMARKS NVARCHAR(255) NULL,
	CREATEDAT DATETIME NOT NULL,
	CREATEDBY CHAR(36) NOT NULL,
	UPDATEDAT DATETIME,
	UPDATEDBY CHAR(36),
	IP NVARCHAR(MAX) NOT NULL,
	ISACTIVE BIT NOT NULL
)