CREATE TABLE SALE_ORDER_HDR(
	ID				CHAR(36) NOT NULL,			
	TRNS_DATE		DATE NOT NULL,
	CASHIER_ID		CHAR(36) NOT NULL,	
	MEMBER_ID		CHAR(36),	
	ORDR_TYPE		NVARCHAR(10),

	TOT_DISC_AMT	NUMERIC(18,2),
	TOT_AMT			NUMERIC(18,2),
	NET_AMT			NUMERIC(18,2),

	REMARKS			NVARCHAR(255),
	CREATEDAT		DATETIME NOT NULL,
	CREATEDBY		CHAR(36) NOT NULL,
	UPDATEDAT		DATETIME,
	UPDATEDBY		CHAR(36),
	IP				NVARCHAR(MAX) NOT NULL,
	ISACTIVE		BIT NOT NULL,
	PRIMARY KEY (ID),

	CONSTRAINT FK_SALE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(Id),
	CONSTRAINT FK_SALE_CASHIER FOREIGN KEY (CASHIER_ID) REFERENCES CASHIER(Id),
)
Go

CREATE TABLE SALE_ORDER_DETL(
	ID				CHAR(36) NOT NULL,
	LINE_ID			INT NOT NULL,	

	STOCKGRP_ID		CHAR(36) NOT NULL,
	STOCKITEM_ID	CHAR(36) NOT NULL,	
	PRICE			NUMERIC(18,2),
	QUANTITY		NUMERIC(18,2),

	DISC_TYPE		NVARCHAR(5),
	DISC_AMOUNT		NUMERIC(18,2),	
	TOT_DISC_AMT	NUMERIC(18,2),
	TOT_AMT	NUMERIC(18,2),
	NET_AMT	NUMERIC(18,2),	

	REMARKS			NVARCHAR(255),
	CREATEDAT		DATETIME NOT NULL,
	CREATEDBY		CHAR(36) NOT NULL,
	UPDATEDAT		DATETIME,
	UPDATEDBY		CHAR(36),
	IP				NVARCHAR(MAX) NOT NULL,
	ISACTIVE		BIT NOT NULL,
	PRIMARY KEY (ID, LINE_ID),
	
	CONSTRAINT FK_SALE_HDR FOREIGN KEY (ID) REFERENCES SALE_ORDER_HDR(ID),	
	CONSTRAINT FK_SALE_STKGRP FOREIGN KEY (STOCKGRP_ID) REFERENCES STOCKGROUP(Id),
	CONSTRAINT FK_SALE_STKITM FOREIGN KEY (STOCKITEM_ID) REFERENCES STOCKITEM(Id),	
)

GO

CREATE TABLE PAYMENT(
	ID				CHAR(36) NOT NULL,
	LINE_ID			INT NOT NULL,	

	PAY_METHOD		NVARCHAR(10) NOT NULL,
	TOT_AMT			NUMERIC(18,2),
	CARD_NUM		NVARCHAR(255),

	REMARKS			NVARCHAR(255),
	CREATEDAT		DATETIME NOT NULL,
	CREATEDBY		CHAR(36) NOT NULL,
	UPDATEDAT		DATETIME,
	UPDATEDBY		CHAR(36),
	IP				NVARCHAR(MAX) NOT NULL,
	ISACTIVE		BIT NOT NULL,
	PRIMARY KEY (ID, LINE_ID),
	
	CONSTRAINT FK_SALE_PAY FOREIGN KEY (ID) REFERENCES SALE_ORDER_HDR(ID),	
)
