DROP Function Fun_OrderList
GO
CREATE Function Fun_OrderList(      
	@ID			CHAR(36)            
) 
RETURNS @RetTable Table                                      
(                                    
	ORDER_ID		CHAR(36),	
	TRNS_DATE		DATE , 
	CASHIER_ID		CHAR(36),
	MEMBER_ID		CHAR(36),	
	ORDR_TYPE		NVARCHAR(10),
	H_TOT_DISC_AMT	NUMERIC(18,2),
	H_TOT_AMT			NUMERIC(18,2),
	H_NET_AMT			NUMERIC(18,2),
	CREATEDAT		DATETIME,
	CREATEDBY		CHAR(36),
	
	LINE_ID			INT,
	STOCKGRP_ID		CHAR(36),
	STOCKITEM_ID	CHAR(36),			
	ITEM_DESC		NVARCHAR(255),
	PRICE			NUMERIC(18,2),
	QUANTITY		NUMERIC(18,2),
	TOT_DISC_AMT	NUMERIC(18,2),
	TOT_AMT			NUMERIC(18,2),
	NET_AMT			NUMERIC(18,2),

	P_LINE_ID		INT,
	PAY_METHOD		NVARCHAR(10),
	PAY_AMT			NUMERIC(18,2),
	CARD_NUM		NVARCHAR(255)
)       
  
As 
     
BEGIN   

INSERT INTO @RetTable (ORDER_ID, TRNS_DATE,	CASHIER_ID,	MEMBER_ID, ORDR_TYPE, H_TOT_DISC_AMT, H_TOT_AMT, H_NET_AMT, CREATEDAT, CREATEDBY,
LINE_ID, STOCKGRP_ID, STOCKITEM_ID,	ITEM_DESC, PRICE, QUANTITY, TOT_DISC_AMT, TOT_AMT, NET_AMT,
P_LINE_ID, PAY_METHOD, PAY_AMT,	CARD_NUM)

SELECT 'xxxxx' + RIGHT(H.ID, 3), H.TRNS_DATE, H.CASHIER_ID, H.MEMBER_ID, H.ORDR_TYPE, 
H.TOT_DISC_AMT, H.TOT_AMT, H.NET_AMT, FORMAT(H.CREATEDAT, 'yyyy-MM-dd HH:mm:ss tt'),H.CREATEDBY,

D.LINE_ID, D.STOCKGRP_ID, D.STOCKITEM_ID, ISNULL(I.Description,I.CODE),
D.PRICE, D.QUANTITY, D.TOT_DISC_AMT, D.TOT_AMT, D.NET_AMT,

P.LINE_ID, P.PAY_METHOD, P.TOT_AMT, P.CARD_NUM

FROM SALE_ORDER_DETL D 
LEFT OUTER JOIN SALE_ORDER_HDR H ON D.ID=H.ID
LEFT OUTER JOIN PAYMENT P ON H.ID=P.ID
LEFT OUTER JOIN STOCKITEM I ON D.STOCKGRP_ID=I.StockGrp_Id AND D.STOCKITEM_ID=I.Id
WHERE D.ID=@ID


RETURN 

END  

